server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.10.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: E:\code\rsa\rsa.pub
    cookieName: LY_TOKEN