server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB  #限制文件上传大小
  resources:
    static-locations: E:/code/java_oncedemo/leyou/leyou-cloud/ly-upload/src/main/resources/static/upload/
  mvc:
    static-path-pattern: /upload/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1